version: "3.9"  # optional since v1.27.0
services:
  agent:
    image: docker.elastic.co/beats/elastic-agent:8.1.3
    hostname: docker-compose-agent
    environment:
      - FLEET_ENROLL=1
      - FLEET_URL
      - FLEET_ENROLLMENT_TOKEN
